# Generated by Django 4.2.5 on 2023-11-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50, verbose_name='Nombre Admin')),
                ('Apellido', models.TextField(max_length=500, verbose_name='Apellido Admin')),
                ('correo', models.TextField(max_length=50, verbose_name='Correo Admin')),
                ('Contraseña', models.TextField(max_length=50, verbose_name='Contra Admin')),
                ('celular', models.IntegerField(verbose_name='Celular Admin')),
                ('Direccion', models.TextField(verbose_name='Direc Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100, verbose_name='Nombre Contacto')),
                ('correo', models.TextField(max_length=50, verbose_name='Correo Contacto')),
                ('celular', models.IntegerField(verbose_name='Celular Contacto')),
                ('Descripcion', models.TextField(verbose_name='Descrip Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50, verbose_name='Nombre Producto')),
                ('categoria', models.TextField(max_length=50, verbose_name='Categoria')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Descripcion Producto')),
                ('imagen', models.ImageField(null=True, upload_to='static/', verbose_name='Imagen')),
                ('existencias', models.IntegerField(verbose_name='Existencia Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50, verbose_name='Nombre Usu')),
                ('Apellido', models.TextField(max_length=500, verbose_name='Apellido Usu')),
                ('correo', models.TextField(max_length=50, verbose_name='Correo Usu')),
                ('Contraseña', models.TextField(max_length=50, verbose_name='Contra Usu')),
            ],
        ),
    ]
