# Generated by Django 4.2.7 on 2023-11-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='Descripcion',
            field=models.TextField(verbose_name='Descripcion Contacto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='existencias',
            field=models.IntegerField(verbose_name='Existencia'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.TextField(max_length=50, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio'),
        ),
    ]
