# Generated by Django 4.2.7 on 2023-11-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_contacto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Contraseña',
            field=models.CharField(max_length=50, verbose_name='Contra Admin'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='correo',
            field=models.EmailField(max_length=50, verbose_name='Correo Admin'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='celular',
            field=models.IntegerField(verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=50, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.TextField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Apellido',
            field=models.TextField(max_length=500, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Contraseña',
            field=models.CharField(max_length=50, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(max_length=50, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.TextField(max_length=50, verbose_name='Nombre'),
        ),
    ]
