# Generated by Django 4.2.7 on 2023-11-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_alter_admin_contraseña_alter_admin_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='correo',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Correo Admin'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Correo'),
        ),
    ]
